### ISSUE TITLE
Not working after a few minutes

### ISSUE THREAD

**Issue by cblong812** [dustindclark/homebridge-envisalink#97] opened 2022-02-14 13:41 UTC
Hi all.  Im new here but cannot seem to get this to work consistently.  It will work upon restart for about 5-15 minutes but then I get the error code below.  I have checked and not other services are connected to the envisalink panel besides the eyezon app on my phone.  It used to be connected to alexa but I have deleted that skill.  Please advise. 

[2/14/2022, 1:33:47 PM] [Envisalink] sendcommand 0301C4
[2/14/2022, 1:33:47 PM] [Envisalink] Failed to connect to Envisalink Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'

**Comment by dustindclark** [comment] 2022-02-28 04:07
This is caused by one of 2 things:

1. your network or your connections (Envisalink or Homebridge) are flakey. Ideally, don't use wifi. An IP conflict can also cause this issue.
2. Some other service is connecting to Envisalink and breaking connections.

For now, I'm closing in favor of #93, which will help this situation. That said, the underlying issue really needs to be fixed on your network.

**Closed as completed by dustindclark** 2022-02-28 04:07 UTC
