### ISSUE TITLE
Actual disconnected (with log and config)

### ISSUE THREAD

**Issue by tomhoag** [dustindclark/homebridge-envisalink#140] opened 2022-10-16 02:43 UTC
I’m not seeing any accessories from my Envisalink 4. I have disabled other plugins. V 1.1.6. Log and config below. Last line in the the log is “Envisalink actual disconnected”

I have double checked IP address and password. 

This log entry looks suspicious:

[15/10/2022, 22:32:24] [Envisalink] Finished initializing platform: undefined

Log:
[15/10/2022, 22:32:11] [Homebridge UI] Homebridge restart request received
[15/10/2022, 22:32:11] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[15/10/2022, 22:32:11] [Homebridge UI] Sending SIGTERM to Homebridge
[15/10/2022, 22:32:11] Got SIGTERM, shutting down Homebridge...
[15/10/2022, 22:32:16] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[15/10/2022, 22:32:21] [HB Supervisor] Restarting Homebridge...
[15/10/2022, 22:32:21] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules -D
[15/10/2022, 22:32:21] [HB Supervisor] Starting Homebridge with custom env: {"DEBUG":"debug"}
[15/10/2022, 22:32:21] [HB Supervisor] Started Homebridge v1.5.0 with PID: 4645
[15/10/2022, 22:32:22] Loaded config.json with 1 accessories and 3 platforms.
[15/10/2022, 22:32:22] Loaded 1 cached accessories from cachedAccessories.
[15/10/2022, 22:32:22] ---
[15/10/2022, 22:32:24] Loaded plugin: homebridge-envisalink@1.1.6
[15/10/2022, 22:32:24] Registering platform 'homebridge-envisalink.Envisalink'
[15/10/2022, 22:32:24] ---
[15/10/2022, 22:32:24] Disabled plugin: homebridge-gpio-device@0.4.9
homebridge-gpio-device API version: 2.7
[15/10/2022, 22:32:24] ---
[15/10/2022, 22:32:24] Disabled plugin: homebridge-nest@4.6.9
[15/10/2022, 22:32:24] ---
[15/10/2022, 22:32:24] Disabled plugin: homebridge-dakota-alert@0.1.0
homebridge-gpio-device API version: 2.7
[15/10/2022, 22:32:24] ---
[15/10/2022, 22:32:24] Loaded plugin: homebridge-config-ui-x@4.50.1
[15/10/2022, 22:32:24] Registering platform 'homebridge-config-ui-x.config'
[15/10/2022, 22:32:24] ---
[15/10/2022, 22:32:24] Loading 3 platforms...
[15/10/2022, 22:32:24] Ignoring config for the platform "Nest" in your config.json as the plugin "homebridge-nest" has been disabled.
[15/10/2022, 22:32:24] [Envisalink] Initializing Envisalink platform...
[15/10/2022, 22:32:24] [Envisalink] Finished initializing platform: undefined
[15/10/2022, 22:32:24] Loading 1 accessories...
[15/10/2022, 22:32:24] Ignoring config for the accessory "DakotaAlert" in your config.json as the plugin "homebridge-dakota-alert" has been disabled.
[15/10/2022, 22:32:24] [Envisalink] Loading accessory from cache: Panic
[15/10/2022, 22:32:24] [Envisalink] Executed didFinishLaunching callback
[15/10/2022, 22:32:24] [Envisalink] Configuring Envisalink platform,  Host: 192.168.1.42 Port: 4025
[15/10/2022, 22:32:24] [Envisalink] Starting Envisalink connection...
[15/10/2022, 22:32:24] [Envisalink] Node alarm proxy started. Proxy is disabled
[15/10/2022, 22:32:24] [Envisalink] Panic buttons disabled. Will not install panic switches.
[15/10/2022, 22:32:24] [Envisalink] No custom commands configured.
[15/10/2022, 22:32:24] Publishing bridge accessory (name: Homebridge 4539, publishInfo: {
  username: '0E:9B:54:B3:45:39',
  port: 51225,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'avahi'
}).
Setup Payload:
X-HM://00240HBDDZLJ6
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 328-34-513 │     
    └────────────┘     
                       
[15/10/2022, 22:32:24] [Envisalink] actual connected
[15/10/2022, 22:32:24] Homebridge v1.5.0 (HAP v0.10.2) (Homebridge 4539) is running on port 51225.
[15/10/2022, 22:32:34] [Envisalink] Envisalink actual disconnected

Plug-in config:

        {
            "host": "192.168.1.42",
            "password": "user",
            "pin": "1006",
            "port": 4025,
            "enableVerboseLogging": true,
            "suppressZoneAccessories": false,
            "suppressClockReset": true,
            "policePanic": {
                "enabled": false,
                "name": "Police Panic"
            },
            "ambulancePanic": {
                "enabled": false,
                "name": "Ambulance Panic"
            },
            "firePanic": {
                "enabled": false,
                "name": "Fire Panic"
            },
            "partitions": [
                {
                    "name": "Alarm",
                    "enableChimeSwitch": true
                }
            ],
            "zones": [
                {
                    "name": "Front Door",
                    "partition": 1,
                    "zoneNumber": 10,
                    "type": "door"
                },
                {
                    "name": "Deck Door",
                    "partition": 1,
                    "zoneNumber": 11,
                    "type": "door"
                },
                {
                    "name": "Side Door",
                    "partition": 1,
                    "zoneNumber": 12,
                    "type": "door"
                },
                {
                    "name": "Garage Basement Door",
                    "partition": 1,
                    "zoneNumber": 13,
                    "type": "door"
                },
                {
                    "name": "Basement Lake Door",
                    "partition": 1,
                    "zoneNumber": 14,
                    "type": "door"
                },
                {
                    "name": "Hallway Motuon",
                    "partition": 1,
                    "zoneNumber": 15,
                    "type": "motion"
                },
                {
                    "name": "Motion Foyer",
                    "partition": 1,
                    "zoneNumber": 16,
                    "type": "motion"
                },
                {
                    "name": "Motion Living Room",
                    "partition": 1,
                    "zoneNumber": 17,
                    "type": "motion"
                },
                {
                    "name": "Motion Basement",
                    "partition": 1,
                    "zoneNumber": 18,
                    "type": "motion"
                },
                {
                    "name": "2nd Floor Smoke",
                    "partition": 1,
                    "zoneNumber": 19,
                    "type": "smoke"
                },
                {
                    "name": "Basement Heat",
                    "partition": 1,
                    "zoneNumber": 20,
                    "type": "smoke"
                },
                {
                    "name": "House to Garage",
                    "partition": 1,
                    "zoneNumber": 9,
                    "type": "door"
                }
            ],
            "platform": "Envisalink"
        }

**Comment by dustindclark** [comment] 2022-10-20 16:28
Can you set `enableVerboseLogging` to true, and post your log here? I've added a debugging step to the readme.

**Comment by tomhoag** [comment] 2022-10-21 14:09
Thanks @dustindclark. The previously posted config above has 'enableVerboseLogging' is set to true.  

I re-enabled the plugin, double checked the config (below) and had the same result.  (log file further below).

Thanks

```
{
            "platform": "Envisalink",
            "host": "192.168.1.42",
            "password": "user",
            "pin": "1006",
            "port": 4025,
            "proxyPort": 4026,
            "enableVerboseLogging": true,
            "suppressZoneAccessories": false,
            "suppressClockReset": true,
            "policePanic": {
                "enabled": false,
                "name": "Police Panic"
            },
            "ambulancePanic": {
                "enabled": false,
                "name": "Ambulance Panic"
            },
            "firePanic": {
                "enabled": false,
                "name": "Fire Panic"
            },
            "partitions": [
                {
                    "name": "Alarm",
                    "enableChimeSwitch": true,
                    "pin": "1006"
                }
            ],
            "zones": [
                {
                    "name": "House to Garage",
                    "partition": 1,
                    "zoneNumber": 9,
                    "type": "door"
                },
                {
                    "name": "Front Door",
                    "partition": 1,
                    "zoneNumber": 10,
                    "type": "door"
                },
                {
                    "name": "Deck Door",
                    "partition": 1,
                    "zoneNumber": 11,
                    "type": "door"
                },
                {
                    "name": "Side Door",
                    "partition": 1,
                    "zoneNumber": 12,
                    "type": "door"
                },
                {
                    "name": "Garage Basement Door",
                    "partition": 1,
                    "zoneNumber": 13,
                    "type": "door"
                },
                {
                    "name": "Basement Lake Door",
                    "partition": 1,
                    "zoneNumber": 14,
                    "type": "door"
                },
                {
                    "name": "Hallway Motion",
                    "partition": 1,
                    "zoneNumber": 15,
                    "type": "motion"
                },
                {
                    "name": "Foyer Motion",
                    "partition": 1,
                    "zoneNumber": 16,
                    "type": "motion"
                },
                {
                    "name": "Living Room Motion",
                    "partition": 1,
                    "zoneNumber": 17,
                    "type": "motion"
                },
                {
                    "name": "Basement Motion",
                    "partition": 1,
                    "zoneNumber": 18,
                    "type": "motion"
                },
                {
                    "name": "2nd Floor Smoke",
                    "partition": 1,
                    "zoneNumber": 19,
                    "type": "smoke"
                },
                {
                    "name": "Basement Heat",
                    "partition": 1,
                    "zoneNumber": 20,
                    "type": "smoke"
                }
            ]
        },
```

and here is the log:

```
[21/10/2022, 10:03:32] [Homebridge UI] Homebridge restart request received
[21/10/2022, 10:03:32] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[21/10/2022, 10:03:32] [Homebridge UI] Sending SIGTERM to Homebridge
[21/10/2022, 10:03:32] Got SIGTERM, shutting down Homebridge...
[21/10/2022, 10:03:37] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[21/10/2022, 10:03:42] [HB Supervisor] Restarting Homebridge...
[21/10/2022, 10:03:42] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules
[21/10/2022, 10:03:42] [HB Supervisor] Started Homebridge v1.5.0 with PID: 7756
[21/10/2022, 10:03:43] Loaded config.json with 2 accessories and 4 platforms.
[21/10/2022, 10:03:44] Loaded 2 cached accessories from cachedAccessories.
[21/10/2022, 10:03:44] ---
[21/10/2022, 10:03:45] Loaded plugin: homebridge-envisalink@1.1.6
[21/10/2022, 10:03:45] Registering platform 'homebridge-envisalink.Envisalink'
[21/10/2022, 10:03:45] ---
[21/10/2022, 10:03:45] Disabled plugin: homebridge-envisalink-ademco@2.0.2
[21/10/2022, 10:03:45] ---
[21/10/2022, 10:03:45] Disabled plugin: homebridge-fakeswitch@0.0.3
[21/10/2022, 10:03:45] ---
[21/10/2022, 10:03:45] Disabled plugin: homebridge-gpio-device@0.4.9
homebridge-gpio-device API version: 2.7
[21/10/2022, 10:03:45] ---
[21/10/2022, 10:03:45] Loaded plugin: homebridge-nest@4.6.9
[21/10/2022, 10:03:45] Registering platform 'homebridge-nest.Nest'
[21/10/2022, 10:03:45] ---
[21/10/2022, 10:03:45] Loaded plugin: homebridge-dakota-alert@0.1.0
homebridge-gpio-device API version: 2.7
[21/10/2022, 10:03:45] Registering accessory 'homebridge-dakota-alert.DakotaAlert'
[21/10/2022, 10:03:45] ---
[21/10/2022, 10:03:45] Loaded plugin: homebridge-config-ui-x@4.50.1
[21/10/2022, 10:03:45] Registering platform 'homebridge-config-ui-x.config'
[21/10/2022, 10:03:45] ---
[21/10/2022, 10:03:45] Loading 4 platforms...
[21/10/2022, 10:03:45] [Nest] Initializing Nest platform...
[21/10/2022, 10:03:45] [Envisalink] Initializing Envisalink platform...
[21/10/2022, 10:03:45] Ignoring config for the platform "Envisalink-Ademco" in your config.json as the plugin "homebridge-envisalink-ademco" has been disabled.
[21/10/2022, 10:03:45] Loading 2 accessories...
[21/10/2022, 10:03:45] [Dakota] Initializing DakotaAlert accessory...
[21/10/2022, 10:03:45] Ignoring config for the accessory "FakeSwitch" in your config.json as the plugin "homebridge-fakeswitch" has been disabled.
[21/10/2022, 10:03:45] [Nest] Fetching Nest devices.
[21/10/2022, 10:03:45] [Envisalink] Configuring Envisalink platform,  Host: 192.168.1.42 Port: 4025
[21/10/2022, 10:03:45] [Envisalink] Starting Envisalink connection...
[21/10/2022, 10:03:45] [Envisalink] Node alarm proxy started.  Listening for connections at: 0.0.0.0:4026
[21/10/2022, 10:03:45] [Envisalink] Panic buttons disabled. Will not install panic switches.
Setup Payload:
X-HM://00240HBDDZLJ6
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 328-34-513 │     
    └────────────┘     
                       
[21/10/2022, 10:03:45] Homebridge v1.5.0 (HAP v0.10.2) (Homebridge 4539) is running on port 51225.
[21/10/2022, 10:03:49] [Nest] initing thermostat "Hallway Thermostat": deviceId: 02AA01AC391301BN structureId: 79f058d0-5862-11e2-8bf7-1231390ba9c1
[21/10/2022, 10:03:49] [Nest] initing home_away_sensor "Home Occupied": deviceId: 79f058d0-5862-11e2-8bf7-1231390ba9c1 structureId: 79f058d0-5862-11e2-8bf7-1231390ba9c1
[21/10/2022, 10:03:55] [Envisalink] Envisalink actual disconnected
```

**Comment by dustindclark** [comment] 2022-10-21 16:03
I'm unable to recreate this problem no matter what combination of bad configs I try. Can you install `v1.1.38-beta.0` and see if the behavior is any different? At a minimum, you should see automatic retries.

Also, try going to `http://192.168.1.42` in a browser and confirm that you can access your device using your configured password. The username is `user`. Once logged in, click on the "Network" tab and post a screenshot here.

**Comment by tomhoag** [comment] 2022-10-21 16:51
After install of v.1.1.38-beta.0:

```[21/10/2022, 12:47:50] [Homebridge UI] Homebridge restart request received
[21/10/2022, 12:47:50] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[21/10/2022, 12:47:50] [Homebridge UI] Sending SIGTERM to Homebridge
[21/10/2022, 12:47:50] Got SIGTERM, shutting down Homebridge...
[21/10/2022, 12:47:55] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[21/10/2022, 12:48:00] [HB Supervisor] Restarting Homebridge...
[21/10/2022, 12:48:00] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules
[21/10/2022, 12:48:00] [HB Supervisor] Started Homebridge v1.5.0 with PID: 11674
[21/10/2022, 12:48:01] Loaded config.json with 2 accessories and 4 platforms.
[21/10/2022, 12:48:02] Loaded 17 cached accessories from cachedAccessories.
[21/10/2022, 12:48:02] ---
[21/10/2022, 12:48:03] Loaded plugin: homebridge-envisalink@1.1.38-beta.0
[21/10/2022, 12:48:03] Registering platform 'homebridge-envisalink.Envisalink'
[21/10/2022, 12:48:03] ---
[21/10/2022, 12:48:03] Disabled plugin: homebridge-envisalink-ademco@2.0.2
[21/10/2022, 12:48:03] ---
[21/10/2022, 12:48:03] Loaded plugin: homebridge-fakeswitch@0.0.3
[21/10/2022, 12:48:03] Registering accessory 'homebridge-fakeswitch.FakeSwitch'
[21/10/2022, 12:48:03] ---
[21/10/2022, 12:48:03] Disabled plugin: homebridge-gpio-device@0.4.9
homebridge-gpio-device API version: 2.7
[21/10/2022, 12:48:03] ---
[21/10/2022, 12:48:03] Loaded plugin: homebridge-nest@4.6.9
[21/10/2022, 12:48:03] Registering platform 'homebridge-nest.Nest'
[21/10/2022, 12:48:03] ---
[21/10/2022, 12:48:03] Loaded plugin: homebridge-dakota-alert@0.1.0
homebridge-gpio-device API version: 2.7
[21/10/2022, 12:48:03] Registering accessory 'homebridge-dakota-alert.DakotaAlert'
[21/10/2022, 12:48:03] ---
[21/10/2022, 12:48:03] Loaded plugin: homebridge-config-ui-x@4.50.1
[21/10/2022, 12:48:03] Registering platform 'homebridge-config-ui-x.config'
[21/10/2022, 12:48:03] ---
[21/10/2022, 12:48:03] Loading 4 platforms...
[21/10/2022, 12:48:03] [Nest] Initializing Nest platform...
[21/10/2022, 12:48:03] [Envisalink] Initializing Envisalink platform...
[21/10/2022, 12:48:03] Ignoring config for the platform "Envisalink-Ademco" in your config.json as the plugin "homebridge-envisalink-ademco" has been disabled.
[21/10/2022, 12:48:03] Loading 2 accessories...
[21/10/2022, 12:48:03] [Dakota] Initializing DakotaAlert accessory...
[21/10/2022, 12:48:03] [FakeSwitch] Initializing FakeSwitch accessory...
[21/10/2022, 12:48:03] [FakeSwitch] Setting switch to true
[21/10/2022, 12:48:03] Failed to find plugin to handle accessory Alarm
[21/10/2022, 12:48:03] Removing orphaned accessory Alarm
[21/10/2022, 12:48:03] Failed to find plugin to handle accessory House to Garage
[21/10/2022, 12:48:03] Removing orphaned accessory House to Garage
[21/10/2022, 12:48:03] Failed to find plugin to handle accessory Front Door
[21/10/2022, 12:48:03] Removing orphaned accessory Front Door
[21/10/2022, 12:48:03] Failed to find plugin to handle accessory Deck Door
[21/10/2022, 12:48:03] Removing orphaned accessory Deck Door
[21/10/2022, 12:48:03] Failed to find plugin to handle accessory Side Door
[21/10/2022, 12:48:03] Removing orphaned accessory Side Door
[21/10/2022, 12:48:03] Failed to find plugin to handle accessory Garage Basement Door
[21/10/2022, 12:48:03] Removing orphaned accessory Garage Basement Door
[21/10/2022, 12:48:03] Failed to find plugin to handle accessory Basement Lake Door
[21/10/2022, 12:48:03] Removing orphaned accessory Basement Lake Door
[21/10/2022, 12:48:03] Failed to find plugin to handle accessory Hallway Motion
[21/10/2022, 12:48:03] Removing orphaned accessory Hallway Motion
[21/10/2022, 12:48:03] Failed to find plugin to handle accessory Foyer Motion
[21/10/2022, 12:48:03] Removing orphaned accessory Foyer Motion
[21/10/2022, 12:48:03] Failed to find plugin to handle accessory Living Room Motion
[21/10/2022, 12:48:03] Removing orphaned accessory Living Room Motion
[21/10/2022, 12:48:03] Failed to find plugin to handle accessory Basement Motion
[21/10/2022, 12:48:03] Removing orphaned accessory Basement Motion
[21/10/2022, 12:48:03] Failed to find plugin to handle accessory Smoke
[21/10/2022, 12:48:03] Removing orphaned accessory Smoke
[21/10/2022, 12:48:03] Failed to find plugin to handle accessory Basement Heat
[21/10/2022, 12:48:03] Removing orphaned accessory Basement Heat
[21/10/2022, 12:48:03] Failed to find plugin to handle accessory Chime
[21/10/2022, 12:48:03] Removing orphaned accessory Chime
[21/10/2022, 12:48:03] Failed to find plugin to handle accessory Zone Bypass
[21/10/2022, 12:48:03] Removing orphaned accessory Zone Bypass
[21/10/2022, 12:48:03] [Nest] Fetching Nest devices.
[21/10/2022, 12:48:04] [Envisalink] Configuring Envisalink platform,  Host: 192.168.1.42 Port: 4025
[21/10/2022, 12:48:04] [Envisalink] Attempting connect to Envisalink..
[21/10/2022, 12:48:04] [Envisalink] Starting Envisalink connection...
[21/10/2022, 12:48:04] [Envisalink] Node alarm proxy started.  Listening for connections at: 0.0.0.0:4026
[21/10/2022, 12:48:04] [Envisalink] Panic buttons disabled. Will not install panic switches.
Setup Payload:
X-HM://00240HBDDZLJ6
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 328-34-513 │     
    └────────────┘     
                       
[21/10/2022, 12:48:04] Homebridge v1.5.0 (HAP v0.10.2) (Homebridge 4539) is running on port 51225.
[21/10/2022, 12:48:08] [Nest] initing thermostat "Hallway Thermostat": deviceId: 02AA01AC391301BN structureId: 79f058d0-5862-11e2-8bf7-1231390ba9c1
[21/10/2022, 12:48:08] [Nest] initing home_away_sensor "Home Occupied": deviceId: 79f058d0-5862-11e2-8bf7-1231390ba9c1 structureId: 79f058d0-5862-11e2-8bf7-1231390ba9c1
[21/10/2022, 12:48:13] [Envisalink] Attempting connect to Envisalink..
[21/10/2022, 12:48:13] [Envisalink] Caught connection error. Sleeping 60 seconds and trying again.  Error: Unknown disconnect occurred.
    at EnvisalinkHomebridgePlatform.handleDisconnect (/var/lib/homebridge/node_modules/homebridge-envisalink/src/platform.ts:123:30)
    at EventEmitter.emit (node:events:527:28)
    at Socket.<anonymous> (/var/lib/homebridge/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:345:16)
    at Socket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[21/10/2022, 12:48:13] [Envisalink] Envisalink actual disconnected
[21/10/2022, 12:49:13] [Envisalink] Starting Envisalink connection...
[21/10/2022, 12:49:13] [Envisalink] Node alarm proxy started.  Listening for connections at: 0.0.0.0:4026
[21/10/2022, 12:49:23] [Envisalink] Attempting connect to Envisalink..
[21/10/2022, 12:49:23] [Envisalink] Caught connection error. Sleeping 60 seconds and trying again.  Error: Unknown disconnect occurred.
    at EnvisalinkHomebridgePlatform.handleDisconnect (/var/lib/homebridge/node_modules/homebridge-envisalink/src/platform.ts:123:30)
    at EventEmitter.emit (node:events:527:28)
    at Socket.<anonymous> (/var/lib/homebridge/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:345:16)
    at Socket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[21/10/2022, 12:49:23] [Envisalink] Envisalink actual disconnected
```

Network screenshot:
![Screen Shot 2022-10-21 at 12 46 27 PM](https://user-images.githubusercontent.com/226088/197248150-2e7efb2d-eac4-431d-9360-b527b06261bc.png)

**Comment by tomhoag** [comment] 2022-10-21 16:53
fwiw -- the Envisalink-Ademco plugin works as expected.  This is probably a Honeywell/Vista20P issue?

Let me know if there's something else you'd like to try, happy to provide additional info.

**Comment by dustindclark** [comment] 2022-10-21 17:25
You definitely can't have multiple concurrent connections (i.e. both this plugin and the Ademco plugin) to the Envisalink device...that's an Envisalink limitation. Otherwise, this plugin should still work with a Honeywell panel (Envisalink API is the same), but I've not tested it because I have a DSC panel (documented as #59). Would love some help testing and getting the Honeywell panel verified if you're interested in continuing to troubleshoot. Can you confirm whether or not there's something else (plugin or otherwise) connected to your Envisalink?

**Comment by tomhoag** [comment] 2022-10-22 02:29
Only one Envisalink plug-in enabled. Nothing else connected to the Envisalink or the vista20p.

**Comment by dustindclark** [comment] 2022-11-02 04:30
Stumped on this. The only thing that I can think of is that the Envisalink-Ademco plugin isn't gracefully closing connections when Homebridge restarts. Leaving that plugin disabled, you could try fully rebooting the OS rather than just restarting Homebridge. You could also try cutting/restoring power to your Envisalink. Let me know if you get a chance to try these.

**Comment by dustindclark** [comment] 2022-11-06 16:53
Closing as a duplicate of #59. If you get a chance to test this, please post on that issue. Thank you.

**Closed as completed by dustindclark** 2022-11-06 16:53 UTC
Labels: question
